version:  '3'
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    volumes:
      - '/app/node_modules'
      - './backend:/app'
    ports:
      - '3001:3001'
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context:  ./frontend
    ports:
      - '3000:3000'
    volumes:
      - '/app/node_modules'
      - './frontend:/app'
  nginx:
    build: ./nginx
    ports:
      - '90:80'