version: '3'
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend 
    ports:
      - '3001:3001'
    volumes:
      - './backend:/app'
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - './frontend:/app'
  