version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./frontend:/app"
    
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - "/app/node_modules"
      - "./backend:/app"

      
