#frontend
FROM node as Pajju
WORKDIR /app
COPY package.json .
RUN npm install
COPY . ./
EXPOSE 3000
RUN npm run build


FROM nginx:1.23-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=Pajju /app/build .
ENTRYPOINT [ "nginx", "-g"  , "daemon off;"]